### PR TITLE
Revert "Гордеева Таисия. Задача 2. Вариант 4. Спящий брадобрей"

### PR DESCRIPTION
**Pull request by TayaGordeeva**
Падали perf тесты, ошибка исправлена

### CODE REVIEW

**Review by maximchhek — APPROVED** [review]

**Review by Applejack2004 — APPROVED** [review]

**Comment by allnes** [comment]
@TayaGordeeva please correct conflict and don't remove not own files

**Comment by TayaGordeeva** [comment]
done

**Comment by allnes** [comment]
Screenshot 2024-12-29 at 15 13 13
you didn't correct

**Comment by TayaGordeeva** [comment]
@allnes fixed
somewhere deleted 3 comments and idon't know where

**Pull request closed without merging**
